version: '3.8'

services:
  backend:
    build: .
    ports:
      - '3000:3000'
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_SSL=${DB_SSL}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRATION=${JWT_EXPIRATION}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_REGION=${AWS_REGION}
      - AWS_BUCKET_NAME=${AWS_BUCKET_NAME}
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - CURRENT_VERSION=${CURRENT_VERSION}
      - ADMIN_ACCESS_PASS=${ADMIN_ACCESS_PASS}
      - BREVO_API_KEY=${BREVO_API_KEY}
      - BASE_URL=${BASE_URL}
      - FRONTEND_URL=${FRONTEND_URL}
      - PLATFORM_FEES=${PLATFORM_FEES}
      - KITCHEN_FEES=${KITCHEN_FEES}
      - DELIVERY_FEES=${DELIVERY_FEES}
      - SUPER_ADMIN_ACCESS_PASS=${SUPER_ADMIN_ACCESS_PASS}
      - PRODUCTION=${PRODUCTION}
    depends_on:
      - redis
    networks:
      - nutri-network

  redis:
    image: redis:alpine
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data
    networks:
      - nutri-network

networks:
  nutri-network:
    driver: bridge

volumes:
  redis_data:
